"""class Person:
    def __init__(self, name, age,address):
        self.name = name
        self.age = age
        self.address = address

    def __str__(self):
        return "Person Name = {0} Person Age = {1} Person Address = {2}".format(self.name,self.age,self.address)


class Employee(Person):
    def __init__(self,name, age, address, post, salary):
        Person.__init__(self, name, age, address)
        self.post = post
        self.salary = salary

    def __str__(self):
        return "{0}, Post = {1} Salary = {2}".format(Person.__str__(self),self.post,self.salary)

class Detail:
    def __init__(self, post,salary):
        self.post = post
        self.salary = salary

    def __str__(self):
        return "Post = {0} Salary = {1}".format(self.post,self.salary)


class Employee(Person):
    def __init__(self, name, age, address, post, salary):
        super().__init__(name, age, address)
        self.post = post
        self.salary = salary
    def __str__(self):
        return "{0}, Post={1}, Salary = {2}".format(Person.__str__(self),self.post,self.salary)


class Employee(Person,Detail):
    def __init__(self,name,age,address,post,salary):
        Person.__init__(self, name, age, address)
        Detail.__init__(self,post,salary)

    def __str__(self):
        return "{0}, {1}".format(Person.__str__(self), Detail.__str__(self)) 



p1 = Person("Pappu",52,"Varanasi")
print(p1)
e1 = Employee("Pappu2",2,"Delhi","bawarchi",20000)
print(e1)
"""



ls = [['Category : DharmikSite', 'No of Matches = 163', 'Total Percentage of Matches with Data Set = 13.71'], 
      ['Category : SchoolOrCollege', 'No of Matches = 325', 'Total Percentage of Matches with Data Set = 27.33'], 
      ['Category : ProgrammingTutorial', 'No of Matches = 128', 'Total Percentage of Matches with Data Set = 10.77'], 
      ['Category : travellingblog', 'No of Matches = 171', 'Total Percentage of Matches with Data Set = 14.38']]
import pandas as pd
import matplotlib.pyplot as plt
dc = {'DharmikSite': 9.6, 'School/College': 87.44, 'ProgrammingTutorial': 9.76, 'TravellingBlog': 11.84}


key = list(dc.keys())

#print(key)



"""
<div class="container-fluid h-100 p-4">
    <div class="table-responsive w-100 p-1 h-100 ">
    <table class = 'table table-bordered table-condensed card-header'>
        {% for key, value in data.items%}
           <tr>
                <th> {{ key }} </th>
                <td> {{ value }} </td>
           </tr>
        {% endfor %}
        </table>
    </div>    
</div>



 

F:\ProjectDjango>C:/Users/Dell/AppData/Local/Programs/Python/Python38/python.exe f:/ProjectDjango/websiteanalyzer/websiteanalyzer/analyzer.py
matchkeywordfrequency =  [{':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1},
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1},
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1},
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
                          {':': 1, 'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, '.': 23, 'Mandirs': 2, ',': 13, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}]
"""

abc = {'DharmikSite': {'Dharmic': 1, 'Heritage': 1, 'Varanasi': 14, 'Mandirs': 2, 'Ghats': 3, 'Rivers': 1, 'everything': 1, 'Home': 1, 'Rameshwar': 4, 'Pandava': 2, 'Kapil': 4, 'Shri': 1, 'Mandir': 9, 'Sarovar': 1, 'Devi': 2, 'Ganga': 5, 'Ghat': 4, 'About': 1, 'The': 9, 'word': 1, 'made': 2, 'two': 1, 'city': 2, 'rivers': 1, 'It': 3, 'holiest': 1, 'Hindus': 1, 'Prakriti': 1, 'first': 1, 'Shiva': 2, 'Vishnu': 1, 'banks': 1, 'numerous': 1, 'place': 3, 'Linga': 1, 'Viswanath': 1, 'River': 3, 'famous': 3, 'morning': 1, 'activities': 1, 'Aarti': 1, 'takes': 1, 'Baba': 1, 'river': 1, 'Places': 1, 'Yatra': 1, 'fourth': 1, 'last': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'hours': 1, 'India': 1}, 
    'School/College': {'Varanasi': 14, 'Home': 1, 'Gallery': 2, 'Shri': 1, 'View': 1, 'Previous': 1, 'Next': 1, 'About': 1, 'The': 9, 'two': 1, 'city': 2, 'It': 3, 'place': 3, 'cultural': 1, 'activities': 1, 'Last': 1, 'Road': 1, 'last': 1, 'Map': 1, 'Contact': 1, 'us': 1, 'get': 1, '24': 1, 'India': 1, '@': 1, "'s": 1, 'World': 1}, 
    'ProgrammingTutorial': {'Home': 1, 'Next': 1, 'About': 1, 'The': 9, 'left': 1, 'place': 3, 'us': 1, 'get': 1, '@': 1, "'s": 1, 'World': 1}, 
    'TravellingBlog': {'Heritage': 1, 'Varanasi': 14, 'Home': 1, 'Festivals': 1, 'Devi': 2, 'Ganga': 5, 'About': 1, 'The': 9, 'city': 2, 'It': 3, 'first': 1, 'banks': 1, 'place': 3, 'River': 3, 'famous': 3, 'cultural': 1, 'takes': 1, 'river': 1, 'Places': 1, 'Road': 1, 'Contact': 1, 'us': 1, 'get': 1, 'back': 1, 'within': 1, '24': 1, 'hours': 1, 'India': 1, "'s": 1, 'World': 1}}
"""
categoryvalue = list(abc.values())
#print(categoryvalue)
frequency = []
for key1, value2 in abc.items():
    print("\n")
    print(key1)
    #print(list(value2.items()))

    key = value2.keys()
    val = value2.values()
    tempdict = {"Words":list(key),"Frequency":val}
    df = pd.DataFrame(tempdict)

    print(df)
    df.to_excel("F://ProjectDjango//websiteanalyzer//templates//Excel//{0}".format(key1),index=False)




res = {}
for line in categoryvalue:
    res.update(line)

print(type(res))

for key, value in res.items():
    print(str(key)+ " : " +str(value))
    """



l1 = [1,2,3]
l2 = [4,5,6]
l3 = []

l3.append(l1)
l3.append(l2)
print(l3)

